version: '3.8'
services:
  siliconflow-ui:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - ALLOWED_ORIGINS=your-domain.com
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    restart: unless-stopped